-- CREATE DATABASE bd_meatprime;

-- CREATE TABLE USUARIOS(
--     CODIGO INT(6) PRIMARY KEY AUTO_INCREMENT,
--     NOME VARCHAR(20) NOT NULL,
--     SOBRENOME VARCHAR(20) NOT NULL,
--     USUARIO VARCHAR(20) NOT NULL,
--     EMAIL VARCHAR(40) NOT NULL,
--     CPF INT(15) NOT NULL,
--     CELULAR VARCHAR(15) NOT NULL,
--     NIVEL TINYINT(1) DEFAULT '0' NOT NULL,
--     ATIVO TINYINT(1) DEFAULT '1' NOT NULL,
--     SENHA VARCHAR(100) NOT NULL,
--     DATA_NASCIMENTO DATE NOT NULL,
--     DATA_CONTRATACAO DATE NOT NULL,
--     SALARIO VARCHAR(10) DEFAULT '0' NOT NULL
-- );

-- CREATE TABLE CATEGORIAS(
--     CODIGO INT(6) primary key AUTO_INCREMENT,
--     NOME_CATEGORIA VARCHAR(50) NOT NULL,
--     CODIGO_AUTOR_CRIADOR INT(6),
--     DATA_CRIACAO DATE,
--     CONSTRAINT CODIGO_AUTOR_CRIADOR FOREIGN KEY (CODIGO_AUTOR_CRIADOR) REFERENCES USUARIOS (CODIGO)
-- );

-- CREATE TABLE PRODUTOS(
--     CODIGO INT(6) PRIMARY KEY AUTO_INCREMENT,
--     TITULO VARCHAR(100) NOT NULL,
--     CODIGO_CATEGORIA INT(6),
--     IMAGEM VARCHAR(50),
--     DESCRICAO VARCHAR(50),
--     PESO VARCHAR(50),
--     PRECO VARCHAR(50),
--     CODIGO_AUTOR_CRIADOR INT(6),
--     DATA_CRIACAO DATE,
--     CONSTRAINT CODIGO_AUTOR_CRIADOR FOREIGN KEY (CODIGO_AUTOR_CRIADOR) REFERENCES USUARIOS (CODIGO),
--     CONSTRAINT CODIGO_CATEGORIA FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIAS (CODIGO)
-- );

-- CREATE TABLE VIDEOS(
--     CODIGO INT(6) primary key AUTO_INCREMENT,
--     titulo VARCHAR(50) NOT NULL,
--     video VARCHAR(50),
--     DESCRICAO VARCHAR (100),
--     CODIGO_AUTOR_CRIADOR INT(6),
--     DATA_CRIACAO DATE,
--     CONSTRAINT VIDEOS FOREIGN KEY (CODIGO_AUTOR_CRIADOR) REFERENCES USUARIOS (CODIGO)
-- );

-- CREATE TABLE CARROSSEL(
--     CODIGO INT(6) primary key AUTO_INCREMENT,
--     CODIGO_IMAGEM VARCHAR (25) NOT NULL,
--     CODIGO_AUTOR_CRIADOR INT(6),
--     DATA_CRIACAO DATE,
--     CONSTRAINT CARROSSEL FOREIGN KEY (CODIGO_AUTOR_CRIADOR) REFERENCES USUARIOS (CODIGO)
-- );

CREATE DATABASE ZukaMeatPrime;

CREATE TABLE USUARIOS(
    CODIGO INT(6) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ENDERECO INT(6),
    CONTRATADO TINYINT (1) NOT NULL DEFAULT '0',
    NOME VARCHAR(25) NOT NULL,
    SOBRENOME VARCHAR(25) NOT NULL,
    USUARIO VARCHAR(25) NOT NULL,
    CELULAR VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    NIVEL VARCHAR(25) NOT NULL,
    SALARIO VARCHAR (10) NOT NULL DEFAULT '0',
    ATIVO TINYINT (1) NOT NULL DEFAULT '1',
    DATA_CONTRATACAO DATE,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE CATEGORIAS(
    CODIGO INT(6) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODIGO_AUTOR INT (6) NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    DATA_CRIACAO DATE NOT NULL,
    ATIVO TINYINT (1) NOT NULL DEFAULT '1',
    CONSTRAINT COD_AUTOR FOREIGN KEY (CODIGO_AUTOR) REFERENCES USUARIOS (CODIGO)
);

CREATE TABLE PRODUTOS(
    CODIGO INT(6) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CODIGO_AUTOR INT(6) NOT NULL,
    CODIGO_CATEGORIA INT(6) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    COD_BARRA VARCHAR(50) NOT NULL,
    PRECO VARCHAR(50) NOT NULL,
    ATIVO TINYINT (1) NOT NULL DEFAULT '1',
    DATA_VALIDADE DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    CONSTRAINT COD_AUTOR_PROD FOREIGN KEY (CODIGO_AUTOR) REFERENCES USUARIOS (CODIGO),
    CONSTRAINT COD_CATEGORIA FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIAS (CODIGO)
);